Audio View: go to measure
thSoft/eclipse-commons pull request #53
Opened 2020-06-21 17:33 UTC by nittka

Proof of concept: add UI control to let the user enter a measure number.
Based on beats per measure and beats per second (extracted from midi),
the time to go to is calculated.
Of course this works only if the tempo or beats per measure do not
change.

2020-07-05 10:59 UTC, nittka commented
I am thinking of including this feature into the refactored audio control.
In order to create reliable results; I would require the lilypond file to contain a comment like 
`%elysium-midi: 6/4, partial 9/16`
Using such a comment, the user indicates that there are no measure or tempo changes, so that the current measure can be calculated. In that case, an additional text field would be shown in the button row, showing the current measure and allowing to enter the measure to go to.

2021-02-07 10:04 UTC, nittka commented
I have updated the code to the new audio control. Rather than having three fields, there is now one textfield - initially empty.
You can enter a measure number here and the approximate time is calculated. Beats per minute are extracted from the midi. Beats per measure are assumed to be 4 by default. The field format allows to override the defaults:
* "6" - go to the 6th measure
* "9:3" - go the 9th measure assuming 3 beats per measure
* "17:5:113" - go to the 17th measure assuming 5 beats per measure and 113 beats per minute

As the field is initially empty and the measure number is updated only if the field is not empty, the visual impact is quite small.

2021-02-23 23:42 UTC, thSoft commented
Could you calculate the time from the tempo signature and tempo change events present in the MIDI file? IMHO this is unfortunately necessary because these can change over time.

2021-02-24 07:55 UTC, nittka commented
I have not worked with midi events, so far. It may be possible (if quite expensive for this feature, as the events would have to be tracked permanently - during playback, when editing the field, when using the slider) to extract *some* more information improving the result, but it will never be perfect. The information about partial measures, measure changes, (repetitions...) in a piece will not be present in the midi, rendering even tracking tempo changes quite useless.

I think, this is an additional little tool. It is useful in some situations, and can easily be igored otherwise. As I said, due to the default (unset), the visual impact is quite small (and could be reduced further by changing the background color of the text field).

2021-02-27 12:38 UTC, nittka commented
As far as I can see, there is no way to extract information about partial measures from the midi file. However, there are events for measure changes (and tempo changes). As you can get (and set) the tick position and the microseconds position from the sequencer, the simplest way would be to ignore tempo change events. Using the measure events (3/4, 6/8,..), you calculate the tick of the start of each measure, set the tick position in the sequencer and ask for the time in microseconds.
That way you can create a Map measure number -> time. For displaying the measure number/going to a position, you then consult this map.
Tempo changes should be handled implicitly, as the sequencer should return the correct microposition change for a tick.

2021-02-27 14:05 UTC, thSoft commented
Yes, that sounds like a great plan, thanks for the investigation! It would be great if you took the effort to implement it.


________________________________
Feladó: Alexander Nittka <notifications@github.com>
Elküldve: Saturday, February 27, 2021 1:38:55 PM
Címzett: thSoft/eclipse-commons <eclipse-commons@noreply.github.com>
Másolatot kap: Dénes Harmath <harmathdenes@gmail.com>; Review requested <review_requested@noreply.github.com>
Tárgy: Re: [thSoft/eclipse-commons] Audio View: go to measure (#53)


As far as I can see, there is no way to extract information about partial measures from the midi file. However, there are events for measure changes (and tempo changes). As you can get (and set) the tick position and the microseconds position from the sequencer, the simplest way would be to ignore tempo change events. Using the measure events (3/4, 6/8,..), you calculate the tick of the start of each measure, set the tick position in the sequencer and ask for the time in microseconds.
That way you can create a Map measure number -> time. For displaying the measure number/going to a position, you then consult this map.
Tempo changes should be handled implicitly, as the sequencer should return the correct microposition change for a tick.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/thSoft/eclipse-commons/pull/53#issuecomment-787066595>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAA42XOBILSI5YQRIMDWU23TBDRV7ANCNFSM4OD6OBUQ>.

2021-02-27 15:09 UTC, nittka commented
I pushed a first prototype. Tempo and time changes should be handled, already.

Partial measures will be dealt with in a further commit.

2021-02-27 16:14 UTC, nittka commented
Now partials are handled as well. \unfoldRepeats in midi cannot be handled, though.

2021-03-13 00:53 UTC, thSoft commented
Thank you very much, the implementation works great as far as I could test! I'd like to have a few UX proposals:
* Add labels before the text fields to make their meanings clear: *Measure:* and *Time in measure:*
* Always update measure number during playback (this makes its meaning even more clear)

2021-03-13 08:53 UTC, nittka commented
I added labels and made minimal adjustments to always show the measure number. With all labels and text fields in a row, the view gets quite wide. So I tried to arrange the new fields to allow quite a compact presentation.
If you are happy with the result, I would clean up the code, possibly moving some of the code so most of the midi stuff is contained in one class and squash everything in one commit.

Please check the tooltip texts. I am not sure if the text for partial is quite clear.

2021-03-24 06:02 UTC, thSoft requested changes
Sorry for the delay!
* Don't hide the "partial" field during playback, only disable it.
* Navigate to the desired point of time also when pressing Enter in the "partial" field.

2021-03-24 06:02 UTC, thSoft commented on org.eclipse.ui.views.midi/src/org/eclipse/ui/views/midi/MidiPlaybackControl.java
> +		partialLabel.setText("Partial:");
```suggestion
		partialLabel.setText("Upbeat:");
```

2021-03-24 06:02 UTC, thSoft commented on org.eclipse.ui.views.midi/src/org/eclipse/ui/views/midi/MidiPlaybackControl.java
> +		partial.setToolTipText("If the score starts with a partial measure,\nplease provide that information!\nFormat examples '1/4', '3/8'");
```suggestion
		partial.setToolTipText("If the score starts with a partial measure,\nplease provide its duration!\nFormat examples '1/4', '3/8'");
```

2021-03-24 06:02 UTC, thSoft commented on org.eclipse.ui.views.midi/src/org/eclipse/ui/views/midi/MidiPlaybackControl.java
> +		measure.setToolTipText("Enter measure number and press return to go to approximate time!");
```suggestion
		measure.setToolTipText("Enter measure number and press Return to go to approximate time!");
```

2021-03-24 08:50 UTC, nittka commented
I have updated the code according to your suggestions (thanks for the help on wording!). I also cleaned up the code - extracting most of the measure control parts into an inner class and squashed everything into one commit.
(If the midi analysis fails (basically if an exception occurs) all the measure controls are hidden. I tested the code by simply returning false in the analyzers calculateMeasureTimes method in debug mode.)

If you have no further change requests, I am happy with the current state.

2021-03-24 10:20 UTC, thSoft approved these changes

2021-03-24 11:36 UTC, merged